 - name: Install nginx
   ansible.builtin.apt:
      name: nginx
      state: present
      update_cache: yes
   notify: restart nginx
   tags:
    - install
    - 
    
 - name: ensure web root directory exists
   ansible.builtin.file:
    path: /{{ nginx_websites_folder }}/{{ item }}
    state: directory
    mode: '0755'
   loop: "{{ applications }}"
   when: inventory_hostname == 'vm-applications'
   tags:
    - setup

 - name: create default page
   ansible.builtin.template:
     src: index.html.j2
     dest: "/{{ nginx_websites_folder }}/{{ item }}/index.html"
     mode: '0644'
   loop: "{{ applications }}"
   when: inventory_hostname == 'vm-applications'
   tags:
    - setup
   
 - name: copy configuration
   ansible.builtin.template:
     src: application.conf.j2
     dest: "/etc/nginx/sites-available/{{ item }}.conf"
     mode: '0644'
   loop: "{{ applications }}"
   when: inventory_hostname == 'vm-applications'
   tags:
    - setup

 - name: create symlink for configuration
   ansible.builtin.file:
     src: "/etc/nginx/sites-available/{{ item }}.conf"
     dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
     state: link
   loop: "{{ applications }}"
   notify: reload nginx
   when: inventory_hostname == 'vm-applications'
   tags:
    - setup
   