- name: Create Nginx config for proxy container
  template:
    src: default.conf.j2
    dest: /opt/ansible/default.conf
    mode: '0644'

- name: Copy proxy docker-compose file
  template:
    src: proxy-compose.yml.j2
    dest: /opt/ansible/proxy-compose.yml
    mode: '0644'

- name: Start proxy container with docker-compose
  shell: docker compose -f proxy-compose.yml up -d
  args:
    chdir: /opt/ansible
