- hosts: applications
  become: true
  roles:

    - docker_install
    - database
    - backend
    - frontend
    - reverse-proxy

- hosts: databases
  become: true
  roles:
    - docker_install
    - database
   
