- name: application deployment using machine 
  hosts: all
  become: true
  vars:
    custom_message: "Welcome to the application deployment"
  tasks:
  - name: install mongodb only on vm-database
    include_tasks: tasks/install_mongodb.yml
    when: inventory_hostname == 'vm-database'

  - name: install nginx only on vm-applications
    include_tasks: tasks/install_nginx.yml
    when: inventory_hostname == 'vm-applications'

  - name: install java only on vm-applications
    include_tasks: tasks/install_java.yml
    when: inventory_hostname == 'vm-applications'

  - name: deploy readme file on all hosts
    include_tasks: tasks/deploy_readme.yml
    when: inventory_hostname in ['vm-database', 'vm-applications']