---

# create /opt/ansible directory if it doesn't exist
- name: Ensure /opt/ansible directory exists
  file: 
   path: /opt/ansible
   state: directory
   mode: '0755'
   
# tasks file for backend
- name: Copy backend docker-compose file
  template:
    src: compose.yml.j2
    dest: /opt/ansible/backend-compose.yml

- name: Start backend container with docker-compose
  shell: docker compose -f /opt/ansible/backend-compose.yml up -d
  args:
    chdir: /opt/ansible
# - name: Ensure backend is reachable via proxy
#   uri:
#     url: "http://192.168.10.12:80/imc"
#     status_code: 200
#   delegate_to: localhost