---
#ensure the /opt/ansible directory exists
- name: Ensure /opt/ansible directory exists
  file:
   path: /opt/ansible
   state: directory
   mode: '0755'

# tasks file for frontend
- name: Copy frontend docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/ansible/frontend-compose.yml

- name: Start frontend container with docker-compose
  shell: docker compose -f /opt/ansible/frontend-compose.yml up -d
  args:
    chdir: /opt/ansible

# - name: Ensure frontend is reachable via proxy
#   uri:
#     url: "http://{{ proxy_host }}:{{ proxy_port }}/"
#     status_code: 200
#     return_content: true
#   delegate_to: localhost
#   register: frontend_proxy_check

# - name: Afficher le résultat du frontend
#   debug:
#     msg: "Le frontend a répondu via le proxy avec le code {{ frontend_proxy_check.status }}"

