---
  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
    tags:
    - web
    - restart

  - name: reload nginx
    ansible.builtin.service:
      name: nginx
      state: reloaded
    tags:
    - web
    - restart