---
# tasks file for docker_install

    
- name: Install Docker Compose Plugin
  include_tasks: install_compose_plugin.yml

- name: Create shared Docker network if not exists
  docker_network:
    name: myapp-network
    state: present
    driver: bridge
