---
# tasks file for docker_install
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: true

- name: Install Python Docker SDK
  apt:
    name: python3-docker
    state: present
    update_cache: true
- name: Create shared Docker network if not exists
  docker_network:
    name: myapp-network
    state: present
    driver: bridge
